source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
project '{{cookiecutter.project_name}}', 'Debug Beta' => :debug, 'Debug Production' => :debug, 'Release Beta' => :release, 'Release Production' => :release

inhibit_all_warnings!
use_frameworks!

def pg_kit
    # pod 'OBKit', :path => '../pg-kit'
    pod 'OBKit', :git => 'git@github.com:pgalchemy/pg-kit.git', :branch => 'develop'
    # pod 'OBKit', :git => 'git@github.com:pgalchemy/pg-kit.git', :tag => '1.0.0'
end

def common_pods
    pg_kit
    pod 'SwiftLint'
end

target '{{cookiecutter.project_name}}' do
    common_pods
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'R.swift'
    pod 'SnapKit'
    pod 'Alamofire'
end

target '{{cookiecutter.project_name}}Tests' do
    common_pods
end
