source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target '{{cookiecutter.project_name}}' do
  pod 'R.swift'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SwiftLint'
end

