# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

default_platform :ios

lane :test do
  # cocoapods

  # test app
  scan( 
      scheme:"{{cookiecutter.project_name}}",
      clean: true,
      output_types: "html,junit")

  # slack(
  #   slack_url: "https://hooks.slack.com/..."
  # )
end

lane :beta do
  # cocoapods

  # increment_build_number

  # build your iOS app
  gym(
    scheme: "{{cookiecutter.project_name}}",
    export_method: "ad-hoc"
  )

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "{{cookiecutter.fabric_api_key}}",
    build_secret: "{{cookiecutter.fabric_build_secret}}"
  )

  # slack(
  #   slack_url: "https://hooks.slack.com/..."
  # )
end

lane :release do
  # cocoapods

  # increment_build_number

  # build your iOS app
  gym(
    scheme: "{{cookiecutter.project_name}}",
    export_method: "app-store"
  )

  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true)

  # slack(
  #   slack_url: "https://hooks.slack.com/..."
  # )
end
